language: node_js
dist: xenial
sudo: false

matrix:
    include:
        - node_js: 6.14
          env: PUBLISH_TO_NPM=true
        - node_js: 12

before_install:
    - >
        if $(dpkg --compare-versions "${TRAVIS_NODE_VERSION}" "le" "12"); then
            nvm install 12
            nvm use 12
        fi

before_script:
    - nvm use ${TRAVIS_NODE_VERSION}

script:
    - >
        if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
            npm run test:unit:cov
        fi
    - >
        if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
            npm run test:cov
        fi

deploy:
    edge: true
    provider: npm
    api_key:
        secure: $NPM_TOKEN
    email: "support@spikkl.nl"
    skip_cleanup: true
    on:
        tags: true
        condition: $PUBLISH_TO_NPM = true